In [51]:
import numpy as np
import pandas as pd
import pyodbc

In [47]:

conn = pyodbc.connect(
    "Driver={SQL Server};"
    "Server=LAPTOP-L9SB4QLJ;"
    "Database=irissql;"
    "Trusted_Connection=yes;"
)

In [43]:
#Pour trouver MSSQL URL
from urllib.parse import quote_plus

# Database connection details
server = 'LAPTOP-L9SB4QLJ'
database = 'irissql'
username = 'LAPTOP-L9SB4QLJ\chaou'
password = ''

# Construct the MSSQL connection URL
if password == '':
    url = f'mssql+pyodbc://{quote_plus(username)}@{server}/{database}?driver=SQL Server'
else:
    url = f'mssql+pyodbc://{quote_plus(username)}:{quote_plus(password)}@{server}/{database}?driver=SQL Server'

# Print the connection URL
print(url)


mssql+pyodbc://LAPTOP-L9SB4QLJ%5Cchaou@LAPTOP-L9SB4QLJ/irissql?driver=SQL Server


In [ ]:
from sqlalchemy import create_engine

In [ ]:
# Create an SQLAlchemy engine
engine = create_engine('mssql+pyodbc://LAPTOP-L9SB4QLJ%5Cchaou@LAPTOP-L9SB4QLJ/irissql?driver=SQL+Server')

In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# Create an SQLAlchemy engine
engine = create_engine('mssql+pyodbc://LAPTOP-L9SB4QLJ%5Cchaou@LAPTOP-L9SB4QLJ/irissql?driver=SQL+Server')

In [ ]:
# Use the engine to read data from the database
T = pd.read_sql(requête, engine)

In [49]:
#Nous pouvons désormais voir à quoi ressemblent les élément de notre variable
T.head()

Sépales.Longueur  EspècesId
0               5.1        0.0
1               4.9        0.0
2               4.7        0.0
3               4.6        0.0
4               5.0        0.0

In [50]:
T.shape

(5, 2)

In [52]:
#Concaténer différentes sources de données
ar1=np.arange(2,20,2).reshape(3,3)


In [53]:
type(ar1)

numpy.ndarray

In [56]:
ar2=ar1+1
ar2

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [55]:
np.concatenate([ar1,ar2])

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [57]:
#Nous pouvons aussi appliquer la concaténation selon l'axe 1
np.concatenate([ar1,ar2],axis=1)

array([[ 2,  4,  6,  3,  5,  7],
       [ 8, 10, 12,  9, 11, 13],
       [14, 16, 18, 15, 17, 19]])

In [60]:
#concaténation avec pandas
ser1=pd.Series(np.random.rand(3),index=[1,2,3])
ser2=pd.Series(np.random.rand(3),index=[4,5,6])


In [61]:
pd.concat([ser1,ser2])

1    0.963970
2    0.120084
3    0.189965
4    0.724551
5    0.765673
6    0.936538
dtype: float64

In [62]:
#Concaténation selon l'axe 1
pd.concat([ser1,ser2],axis=1)

0         1
1  0.963970       NaN
2  0.120084       NaN
3  0.189965       NaN
4       NaN  0.724551
5       NaN  0.765673
6       NaN  0.936538

In [68]:
#Fusionner différentes sources de données
df1=pd.DataFrame({'salarié':['Eric','Hapsa','Elise','Xin'],'groupe':['Technicien','Ingénieur','Ingénieur','Technicien']})
df2=pd.DataFrame({'salarié':['Hapsa','Elise','Eric','Xin'],'data_embauche':[2001,1988,2012,2016]})

In [71]:
df3=pd.merge(df1,df2)

In [72]:
df3

salarié      groupe  data_embauche
0    Eric  Technicien           2012
1   Hapsa   Ingénieur           2001
2   Elise   Ingénieur           1988
3     Xin  Technicien           2016

In [73]:
df4=pd.DataFrame({'groupe':['Technicien','Ingénieur'],'Superviseur':['Carlos','Amine']})

In [74]:
print(pd.merge(df3,df4))

  salarié      groupe  data_embauche Superviseur
0    Eric  Technicien           2012      Carlos
1     Xin  Technicien           2016      Carlos
2   Hapsa   Ingénieur           2001       Amine
3   Elise   Ingénieur           1988       Amine


In [76]:
df5=pd.DataFrame({'groupe':['Technicien','Technicien','Ingénieur','Ingénieur'],'compétences':['tableurs','maintenance','tableurs','recherche opérationnelle']})

In [77]:
print(pd.merge(df3,df5))

  salarié      groupe  data_embauche               compétences
0    Eric  Technicien           2012                  tableurs
1    Eric  Technicien           2012               maintenance
2     Xin  Technicien           2016                  tableurs
3     Xin  Technicien           2016               maintenance
4   Hapsa   Ingénieur           2001                  tableurs
5   Hapsa   Ingénieur           2001  recherche opérationnelle
6   Elise   Ingénieur           1988                  tableurs
7   Elise   Ingénieur           1988  recherche opérationnelle


In [78]:
df6=pd.DataFrame({'Nom':['Hapsa','Elise','Xin','Amine'],'Salaire':[90000,100000,80000,100000]})

In [83]:
#Utiliser les fonctions left_on et right_on
print(pd.merge(df3,df6, left_on='salarié', right_on='Nom'))

  salarié      groupe  data_embauche    Nom  Salaire
0   Hapsa   Ingénieur           2001  Hapsa    90000
1   Elise   Ingénieur           1988  Elise   100000
2     Xin  Technicien           2016    Xin    80000


In [87]:
#Supprimer la redondance
df7=pd.merge(df3,df6,left_on='salarié',right_on='Nom').drop('Nom',axis=1)

In [88]:
df7

salarié      groupe  data_embauche  Salaire
0   Hapsa   Ingénieur           2001    90000
1   Elise   Ingénieur           1988   100000
2     Xin  Technicien           2016    80000

In [89]:
#Réliser une jointure
pd.merge(df3,df6,left_on='salarié',right_on='Nom',how='outer').drop('Nom',axis=1)

salarié      groupe  data_embauche   Salaire
0    Eric  Technicien         2012.0       NaN
1   Hapsa   Ingénieur         2001.0   90000.0
2   Elise   Ingénieur         1988.0  100000.0
3     Xin  Technicien         2016.0   80000.0
4     NaN         NaN            NaN  100000.0

In [90]:
#Réaliser une jointure à gauche 
pd.merge(df3,df6,left_on='salarié',right_on='Nom',how='left').drop('Nom',axis=1)

salarié      groupe  data_embauche   Salaire
0    Eric  Technicien           2012       NaN
1   Hapsa   Ingénieur           2001   90000.0
2   Elise   Ingénieur           1988  100000.0
3     Xin  Technicien           2016   80000.0

In [92]:
#Réaliser une jointure à droite
pd.merge(df3,df6,left_on='salarié',right_on='Nom',how='right').drop('Nom',axis=1)

salarié      groupe  data_embauche  Salaire
0   Hapsa   Ingénieur         2001.0    90000
1   Elise   Ingénieur         1988.0   100000
2     Xin  Technicien         2016.0    80000
3     NaN         NaN            NaN   100000

In [93]:
"""Parfois, ça arrive que deux dataframe aient un conflit dans le sens où il y a le même nom de colonnes mais 
les données désignent des éléments différents. L'option suffix permet alos de faire face à cela.
Regardons de suite un exemple, On considère DF8, en prenant les colonnes salarié et classement.
"""
df8=pd.DataFrame({'Salarié':['Eric','Hapsa','Elise','Xin'],'Classement':[4,1,2,3]})
df9=pd.DataFrame({'Salarié':['Eric','Hapsa','Elise','Xin'],'Classement':[4,1,3,2]})

In [94]:
"""Sauf qu'ici le classement peut être par exemple, sur des mois différents ou des années différentes.
Nous utilisons alors la fonction merge, mais en précisnat cette fois-ci, que la clé c'est bien Salarié"""
pd.merge(df8,df9,on='Salarié')


Salarié  Classement_x  Classement_y
0    Eric             4             4
1   Hapsa             1             1
2   Elise             2             3
3     Xin             3             2

In [96]:
"""Nous avons bien classement X et classement Y, aux quels nous pouvons préciser des suffixes avec l'option Suffix, par exemple ici
Novembre et Décembre"""
pd.merge(df8,df9,on='Salarié',suffixes=['Novembre','Decembre'])

Salarié  ClassementNovembre  ClassementDecembre
0    Eric                   4                   4
1   Hapsa                   1                   1
2   Elise                   2                   3
3     Xin                   3                   2