In [37]:
#Manipuler les données quantitatives avec numpy
import numpy as np
import pandas as pd

In [8]:
#Exemple
ar=np.array([1,2,3,4])

In [9]:
ar

array([1, 2, 3, 4])

In [10]:
ar.dtype

dtype('int32')

In [11]:
type(ar)

numpy.ndarray

In [12]:
print("dimension=",ar.ndim,"taille=",ar.size,"forme=",ar.shape)

dimension= 1 taille= 4 forme= (4,)


In [13]:
ar[1]

2

In [14]:
#Indexer à partir de la fin du tableau
print("ar[-1]=",ar[-1],"et ar[-2]=",ar[-2])

ar[-1]= 4 et ar[-2]= 3


In [15]:
#Tableau multidimensionnel
ar1=np.array([[1,2,3],[4,5,6]])

In [16]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#Pour accéder à l'élément quatre
ar1[1,0]

4

In [18]:
#Modifiant la valeur d'un élément donné
ar1[0,0]=7

In [19]:
ar1

array([[7, 2, 3],
       [4, 5, 6]])

In [23]:
#Découpage
#Exemple
ar2=np.arange(0,20,3)
ar2

array([ 0,  3,  6,  9, 12, 15, 18])

In [21]:
#le tableau "ar3" contenant les cinq premiers éléments de "ar2"
ar3=ar2[:5]

In [22]:
ar3

array([ 0,  3,  6,  9, 12])

In [24]:
#Découpage de ar2 jusqu'à l'élément 3 et avec un pas de 2
ar3[:4:2]

array([0, 6])

In [25]:
#Nous allons jusqu'à l'indice trois puis nous inversons notre tableau
ar3[3::-1]

array([9, 6, 3, 0])

In [26]:
#Remodelage
ar4=ar1.reshape(3,2)

In [27]:
ar4

array([[7, 2],
       [3, 4],
       [5, 6]])

In [39]:
#Aborder les techniques d'encodage
df=pd.DataFrame({'Salarié':['Eric','Elise','Hapsa','Xin'],'Genre':['Homme','Femme','Femme','Homme'],'groupe':['Technicien','Ingénieur','PhD','Technicien'],'Date_embauche':[2016,1988,2012,2001],'Salaire':[30000,100000,60000,60000]})


In [40]:
#Création d'une Copie de notre DataFrame
df1=df.copy()

In [41]:
#encodage numérique avec pandas
pré_traitement={"groupe":{"PhD":1,"Ingénieur":2,"Technicien":3}}

In [42]:
df1.replace(pré_traitement,inplace=True)
df1

Salarié  Genre  groupe  Date_embauche  Salaire
0    Eric  Homme       3           2016    30000
1   Elise  Femme       2           1988   100000
2   Hapsa  Femme       1           2012    60000
3     Xin  Homme       3           2001    60000

In [43]:
#encodage numérique avec scikit-learn
from sklearn.preprocessing import LabelEncoder
df['groupe_encodé']=LabelEncoder().fit_transform(df['groupe'])

In [44]:
#Pour modifier l'ordre qui est par défaut l'ordre alphabétique, nous allons utiliser la fct Map de pandas
df['groupe_encodé']=df['groupe'].map({'PhD':1,'Ingénieur':2,'Technicien':3})

In [45]:
df[['groupe','groupe_encodé']]

groupe  groupe_encodé
0  Technicien              3
1   Ingénieur              2
2         PhD              1
3  Technicien              3

In [ ]:
#Encodage on