In [2]:
#Manipuler les données quantitatives avec numpy
import numpy as np

In [8]:
#Exemple
ar=np.array([1,2,3,4])

In [9]:
ar

array([1, 2, 3, 4])

In [10]:
ar.dtype

dtype('int32')

In [11]:
type(ar)

numpy.ndarray

In [12]:
print("dimension=",ar.ndim,"taille=",ar.size,"forme=",ar.shape)

dimension= 1 taille= 4 forme= (4,)


In [13]:
ar[1]

2

In [14]:
#Indexer à partir de la fin du tableau
print("ar[-1]=",ar[-1],"et ar[-2]=",ar[-2])

ar[-1]= 4 et ar[-2]= 3


In [15]:
#Tableau multidimensionnel
ar1=np.array([[1,2,3],[4,5,6]])

In [16]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#Pour accéder à l'élément quatre
ar1[1,0]

4

In [18]:
#Modifiant la valeur d'un élément donné
ar1[0,0]=7

In [19]:
ar1

array([[7, 2, 3],
       [4, 5, 6]])

In [23]:
#Découpage
#Exemple
ar2=np.arange(0,20,3)
ar2

array([ 0,  3,  6,  9, 12, 15, 18])

In [21]:
#le tableau "ar3" contenant les cinq premiers éléments de "ar2"
ar3=ar2[:5]

In [22]:
ar3

array([ 0,  3,  6,  9, 12])

In [24]:
#Découpage de ar2 jusqu'à l'élément 3 et avec un pas de 2
ar3[:4:2]

array([0, 6])

In [25]:
#Nous allons jusqu'à l'indice trois puis nous inversons notre tableau
ar3[3::-1]

array([9, 6, 3, 0])

In [26]:
#Remodelage
ar4=ar1.reshape(3,2)

In [27]:
ar4

array([[7, 2],
       [3, 4],
       [5, 6]])