In [37]:
#Manipuler les données quantitatives avec numpy
import numpy as np
import pandas as pd

In [8]:
#Exemple
ar=np.array([1,2,3,4])

In [9]:
ar

array([1, 2, 3, 4])

In [10]:
ar.dtype

dtype('int32')

In [11]:
type(ar)

numpy.ndarray

In [12]:
print("dimension=",ar.ndim,"taille=",ar.size,"forme=",ar.shape)

dimension= 1 taille= 4 forme= (4,)


In [13]:
ar[1]

2

In [14]:
#Indexer à partir de la fin du tableau
print("ar[-1]=",ar[-1],"et ar[-2]=",ar[-2])

ar[-1]= 4 et ar[-2]= 3


In [15]:
#Tableau multidimensionnel
ar1=np.array([[1,2,3],[4,5,6]])

In [16]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
#Pour accéder à l'élément quatre
ar1[1,0]

4

In [18]:
#Modifiant la valeur d'un élément donné
ar1[0,0]=7

In [19]:
ar1

array([[7, 2, 3],
       [4, 5, 6]])

In [23]:
#Découpage
#Exemple
ar2=np.arange(0,20,3)
ar2

array([ 0,  3,  6,  9, 12, 15, 18])

In [21]:
#le tableau "ar3" contenant les cinq premiers éléments de "ar2"
ar3=ar2[:5]

In [22]:
ar3

array([ 0,  3,  6,  9, 12])

In [24]:
#Découpage de ar2 jusqu'à l'élément 3 et avec un pas de 2
ar3[:4:2]

array([0, 6])

In [25]:
#Nous allons jusqu'à l'indice trois puis nous inversons notre tableau
ar3[3::-1]

array([9, 6, 3, 0])

In [26]:
#Remodelage
ar4=ar1.reshape(3,2)

In [27]:
ar4

array([[7, 2],
       [3, 4],
       [5, 6]])

In [39]:
#Aborder les techniques d'encodage
df=pd.DataFrame({'Salarié':['Eric','Elise','Hapsa','Xin'],'Genre':['Homme','Femme','Femme','Homme'],'groupe':['Technicien','Ingénieur','PhD','Technicien'],'Date_embauche':[2016,1988,2012,2001],'Salaire':[30000,100000,60000,60000]})


In [40]:
#Création d'une Copie de notre DataFrame
df1=df.copy()

In [41]:
#encodage numérique avec pandas
pré_traitement={"groupe":{"PhD":1,"Ingénieur":2,"Technicien":3}}

In [42]:
df1.replace(pré_traitement,inplace=True)
df1

Salarié  Genre  groupe  Date_embauche  Salaire
0    Eric  Homme       3           2016    30000
1   Elise  Femme       2           1988   100000
2   Hapsa  Femme       1           2012    60000
3     Xin  Homme       3           2001    60000

In [43]:
#encodage numérique avec scikit-learn
from sklearn.preprocessing import LabelEncoder
df['groupe_encodé']=LabelEncoder().fit_transform(df['groupe'])

In [44]:
#Pour modifier l'ordre qui est par défaut l'ordre alphabétique, nous allons utiliser la fct Map de pandas
df['groupe_encodé']=df['groupe'].map({'PhD':1,'Ingénieur':2,'Technicien':3})

In [45]:
df[['groupe','groupe_encodé']]

groupe  groupe_encodé
0  Technicien              3
1   Ingénieur              2
2         PhD              1
3  Technicien              3

In [46]:
#Encodage one-hot
pd.get_dummies(df['Genre'],prefix='Genre')

Genre_Femme  Genre_Homme
0            0            1
1            1            0
2            1            0
3            0            1

In [47]:
"""L'avantage de l'encodage One-hot est de ne pas pondérer une valeur de manière incorrecte. Néanmoins, l'inconvénient est d'ajouter plus de colonnes à l'ensemble de données"""

"L'avantage de l'encodage One-hot est de ne pas pondérer une valeur de manière incorrecte. Néanmoins, l'inconvénient est d'ajouter plus de colonnes à l'ensemble de données"

In [48]:
#Manipuler les données textuelles avec pandas
données=['valérie','Omar','MAHA','HAPSA']

In [49]:
#Standardiser les données en utilisant la fonction capitalize
[s.capitalize() for s in données]

['Valérie', 'Omar', 'Maha', 'Hapsa']

In [ ]:
"""Mais le problème avec la fonction capitalize de python, c'est que dès que notre liste contient par exemple un élément vide:
None, alors une erreur est affichée indiquant que le type None n a pas d'attribut capitalize.
Pour faire face à cela, nous allons alors utiliser la librairie pandas"""

In [50]:
données=['valérie','Omar','MAHA','haspsa',None]

In [53]:
import pandas as pd
prénom=pd.Series(données)#Nous créons une série dans laquelle nous allons stocker nos données
prénom

0    valérie
1       Omar
2       MAHA
3     haspsa
4       None
dtype: object

In [54]:
prénom.str.capitalize()

0    Valérie
1       Omar
2       Maha
3     Haspsa
4       None
dtype: object

In [55]:
#Ecrire tout en miniscules avec la fonction lower
prénom.str.lower()

0    valérie
1       omar
2       maha
3     haspsa
4       None
dtype: object

In [56]:
#Ecrire tout en majuscule avec la fonction upper
prénom.str.upper()

0    VALÉRIE
1       OMAR
2       MAHA
3     HASPSA
4       None
dtype: object

In [57]:
#Il est possible de calculer la longueur de la chaine en utilisant la fonction length
prénom.str.len()

0    7.0
1    4.0
2    4.0
3    6.0
4    NaN
dtype: float64

In [58]:
#ou encore, rajouter un nouveau prénom à notre série
prénom[5]="Oliver"
prénom

0    valérie
1       Omar
2       MAHA
3     haspsa
4       None
5     Oliver
dtype: object

In [59]:
#La fonction startswith qui indique la valeur true quand le prénom commence par o et false sinon
prénom.str.startswith('o')

0    False
1    False
2    False
3    False
4     None
5    False
dtype: object

In [61]:
"""La fonction startswith() est une fonction très intéressante puisqu'elle nous permet de filtrer par exemple, uniquement 
un certain nombre d'élément. D'ailleurs, regardons ici un affichage en utilisant la boucle for"""
for p in prénom:
    if p!= None and p.startswith('O')==True:print(p)

Omar
Oliver


In [62]:
#Une autre fonction très utile avec pandas est le Split(): ça permet de composer par exemple un nom et prénom qui seraient 
#attachés en mettant le prénom d'un côté et le nom d'un autre côté
#Exp:
prénom=pd.Series(['Omar So','Maha To','Hapsa Di'])
prénom

0     Omar So
1     Maha To
2    Hapsa Di
dtype: object

In [63]:
prénom.str.split()

0     [Omar, So]
1     [Maha, To]
2    [Hapsa, Di]
dtype: object

In [64]:
#Par ailleurs, il est possible d'extraire uniquement une partie du texte qui nous intéresserait, par exemple ici dans notre cas,
#nous allons nous intéresser à l'extraction uniquement du prénom 
prénom.str.extract('([A-Za-Z]+)')

error: bad character range a-Z at position 5

In [65]:
prénom.str.extract('([a-zA-Z]+)')

0
0   Omar
1   Maha
2  Hapsa

In [74]:
#Manipuler des données textuelles avec NLTK
import nltk
from nltk.tokenize import WordPunctTokenizer

In [75]:
Description=open("exemple_texte.txt","r")

In [76]:
Description

<_io.TextIOWrapper name='exemple_texte.txt' mode='r' encoding='cp1252'>

In [77]:
Contenu = Description.read()
print (Contenu)

De nos jours, l'explosion du volume et de la variété des données ne laisse plus planer de doute : le rôle du data scientist sera central dans les années à venir. Si vous êtes data scientist ou que vous souhaitez travailler avec Python, ce cours est pour vous. Omar Souissi, professeur associé en technologie de l'information et techniques d'optimisation, vous aide à acquérir les bases indispensables pour faire de la data science avec Python. Vous découvrirez comment utiliser deux bibliothèques indispensables, à savoir NumPy et Pandas. Vous verrez également quelques études de cas qui vous permettront d'assimiler facilement les différentes notions de Python pour l'analyse de données


In [85]:
#Découpage en mots
token=Contenu.split(" ")

In [86]:
token

['De',
 'nos',
 'jours,',
 "l'explosion",
 'du',
 'volume',
 'et',
 'de',
 'la',
 'variété',
 'des',
 'données',
 'ne',
 'laisse',
 'plus',
 'planer',
 'de',
 'doute',
 ':',
 'le',
 'rôle',
 'du',
 'data',
 'scientist',
 'sera',
 'central',
 'dans',
 'les',
 'années',
 'Ã\xa0',
 'venir.',
 'Si',
 'vous',
 'êtes',
 'data',
 'scientist',
 'ou',
 'que',
 'vous',
 'souhaitez',
 'travailler',
 'avec',
 'Python,',
 'ce',
 'cours',
 'est',
 'pour',
 'vous.',
 'Omar',
 'Souissi,',
 'professeur',
 'associé',
 'en',
 'technologie',
 'de',
 "l'information",
 'et',
 'techniques',
 "d'optimisation,",
 'vous',
 'aide',
 'Ã\xa0',
 'acquérir',
 'les',
 'bases',
 'indispensables',
 'pour',
 'faire',
 'de',
 'la',
 'data',
 'science',
 'avec',
 'Python.',
 'Vous',
 'découvrirez',
 'comment',
 'utiliser',
 'deux',
 'bibliothèques',
 'indispensables,',
 'Ã\xa0',
 'savoir',
 'NumPy',
 'et',
 'Pandas.',
 'Vous',
 'verrez',
 'également',
 'quelques',
 'études',
 'de',
 'cas',
 'qui',
 'vous',
 'p

In [84]:
nltk.word_tokenize(Contenu)

LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/english.pickle

  Searched in:
    - 'C:\\Users\\chaou/nltk_data'
    - 'C:\\Users\\chaou\\anaconda3\\nltk_data'
    - 'C:\\Users\\chaou\\anaconda3\\share\\nltk_data'
    - 'C:\\Users\\chaou\\anaconda3\\lib\\nltk_data'
    - 'C:\\Users\\chaou\\AppData\\Roaming\\nltk_data'
    - 'C:\\nltk_data'
    - 'D:\\nltk_data'
    - 'E:\\nltk_data'
    - ''
**********************************************************************


In [95]:
nltk.download('punkt')
nltk.word_tokenize(Contenu)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\chaou\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['De',
 'nos',
 'jours',
 ',',
 "l'explosion",
 'du',
 'volume',
 'et',
 'de',
 'la',
 'variété',
 'des',
 'données',
 'ne',
 'laisse',
 'plus',
 'planer',
 'de',
 'doute',
 ':',
 'le',
 'rôle',
 'du',
 'data',
 'scientist',
 'sera',
 'central',
 'dans',
 'les',
 'années',
 'Ã',
 'venir',
 '.',
 'Si',
 'vous',
 'êtes',
 'data',
 'scientist',
 'ou',
 'que',
 'vous',
 'souhaitez',
 'travailler',
 'avec',
 'Python',
 ',',
 'ce',
 'cours',
 'est',
 'pour',
 'vous',
 '.',
 'Omar',
 'Souissi',
 ',',
 'professeur',
 'associé',
 'en',
 'technologie',
 'de',
 "l'information",
 'et',
 'techniques',
 "d'optimisation",
 ',',
 'vous',
 'aide',
 'Ã',
 'acquérir',
 'les',
 'bases',
 'indispensables',
 'pour',
 'faire',
 'de',
 'la',
 'data',
 'science',
 'avec',
 'Python',
 '.',
 'Vous',
 'découvrirez',
 'comment',
 'utiliser',
 'deux',
 'bibliothèques',
 'indispensables',
 ',',
 'Ã',
 'savoir',
 'NumPy',
 'et',
 'Pandas',
 '.',
 'Vous',
 'verrez',
 'également',
 'quelques',
 'études',
 '

In [89]:
tokenizer=nltk.RegexpTokenizer('r\w+')

In [91]:
Sac_de_mots=tokenizer.tokenize(Contenu)
Sac_de_mots

['rs',
 'riÃ',
 'rÃ',
 'ra',
 'ral',
 'ravailler',
 'rs',
 'rofesseur',
 'rmation',
 'rir',
 're',
 'rirez',
 'rrez',
 'rmettront',
 'rentes']

In [96]:
stopwords=nltk.corpus.stopwords.words('french')
stopwords[:10]

['au', 'aux', 'avec', 'ce', 'ces', 'dans', 'de', 'des', 'du', 'elle']

In [93]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\chaou\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [97]:
Filtre=[]
for w in Sac_de_mots[1:]:
    if w not in stopwords:
        Filtre.append(w)

In [99]:
Filtre

['riÃ',
 'rÃ',
 'ra',
 'ral',
 'ravailler',
 'rs',
 'rofesseur',
 'rmation',
 'rir',
 're',
 'rirez',
 'rrez',
 'rmettront',
 'rentes']

In [100]:
Filtre.count('Python')

0